# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: db

  chrome:
    image: browserless/chrome:latest
    ports:
      - "3000:3000"
    environment:
      - ALLOWED_HOSTS=*

  grafana:
    image: grafana/grafana
    ports:
      - "4000:3000"
    environment:
      GF_INSTALL_PLUGINS: "grafana-piechart-panel"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - loki

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    environment:
      - "LOKI_STORAGE_TYPE=mem"
      - "LOKI_ADDR=0.0.0.0:3100"
    volumes:
      - loki-storage:/data
    networks:
      - loki

volumes:
  grafana-storage:
  loki-storage:
    
networks:
  loki: