apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres-statefulset
  selector:
    app: postgres
    task: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: "postgres-svc"
  replicas: 1 
  updateStrategy:
    type: RollingUpdate
  
  selector:
    matchLabels:
      app: postgres

  
  volumeClaimTemplates:
    - metadata:
        name: postgres-disc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
  
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.1
          volumeMounts:
            - name: postgres-disc
              mountPath: /data
          ports:
            - containerPort: 5432
              name: postgres-statefulset
          env:
            - name: POSTGRES_DB
              value: $POSTGRES_DB
            - name: POSTGRES_USER
              value: $POSTGRES_USER
            - name: POSTGRES_PASSWORD
              value: $POSTGRES_PASSWORD
            - name: PGDATA
              value: /data/pgdata

