apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: kube-prom-stack
    meta.helm.sh/release-namespace: observability
  labels:
    app: kube-prometheus-stack-alertmanager-undermove
    app.kubernetes.io/instance: kube-prom-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 45.5.0
    chart: kube-prometheus-stack-45.5.0
    heritage: Helm
    release: kube-prom-stack
  name: kube-prom-stack-kube-prome-alertmanager-undermove
  namespace: tralebot-prod
spec:
  endpoints:
    - path: /metrics
      port: http
  namespaceSelector:
    matchNames:
      - tralebot-prod
  selector:
    matchLabels:
      app: tralebot
      app.kubernetes.io/part-of: tralebot
