apiVersion: v1
kind: Service
metadata:
  name: tralebot-service
spec:
  selector:
    app: tralebot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1402
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tralebot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tralebot
  template:
    metadata:
      labels:
        app: tralebot
    spec:
      containers:
        - name: tralebot-container
          image: undermove/tralebot:latest
          ports:
            - containerPort: 1402
          env:
            - name: ConnectionStrings__TraleBotDb
              valueFrom:
                secretKeyRef:
                  name: tralebot-secrets
                  key: TRALEBOT_DB_CONNECTION_STRING
            - name: BotConfiguration__WebhookToken
              valueFrom:
                secretKeyRef:
                  name: tralebot-secrets
                  key: TRALEBOT_WEBHOOK_TOKEN
            - name: BotConfiguration__Token
              valueFrom:
                secretKeyRef:
                  name: tralebot-secrets
                  key: TRALEBOT_CONFIGURATION_TOKEN
#            - name: BotConfiguration__HostAddress
#              valueFrom:
#                secretKeyRef:
#                  name: tralebot-secrets
#                  key: TRALEBOT_SERVER_HOST
#            - name: BotConfiguration__PaymentProviderToken
#              valueFrom:
#                secretKeyRef:
#                  name: tralebot-secrets
#                  key: TRALEBOT_PAYMENT_PROVIDER_TOKEN
#            - name: OpenAiConfiguration__ApiKey
#              valueFrom:
#                secretKeyRef:
#                  name: tralebot-secrets
#                  key: TRALEBOT_OPENAI_TOKEN

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tralebot-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - tralebot.com
      secretName: tls-secret
  rules:
    - host: tralebot.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tralebot-service
                port:
                  number: 80

---

apiVersion: v1
kind: Secret
metadata:
  name: tralebot-secrets
type: Opaque
data:
  TRALEBOT_DB_CONNECTION_STRING: $KUBE_TRALEBOT_DB_CONNECTION_STRING
  TRALEBOT_WEBHOOK_TOKEN: $TRALEBOT_WEBHOOK_TOKEN
  TRALEBOT_CONFIGURATION_TOKEN: $TRALEBOT_CONFIGURATION_TOKEN
#  TRALEBOT_SERVER_HOST: $TRALEBOT_SERVER_HOST
#  TRALEBOT_PAYMENT_PROVIDER_TOKEN: $TRALEBOT_PAYMENT_PROVIDER_TOKEN
#  TRALEBOT_OPENAI_TOKEN: $TRALEBOT_OPENAI_TOKEN
---


