apiVersion: v1
kind: Service
metadata:
  name: tralebot-service
spec:
  selector:
    app: tralebot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1402
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tralebot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tralebot
  template:
    metadata:
      labels:
        app: tralebot
    spec:
      containers:
        - name: tralebot-container
          image: undermove/tralebot:latest
          ports:
            - containerPort: 1402
          env:
            - name: TRALEBOT_CONFIGURATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tralebot-secrets
                  key: TRALEBOT_CONFIGURATION_TOKEN
            - name: TRALEBOT_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: tralebot-secrets
                  key: TRALEBOT_SERVER_HOST
            - name: TRALEBOT_WEBHOOK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tralebot-secrets
                  key: TRALEBOT_WEBHOOK_TOKEN
            - name: TRALEBOT_PAYMENT_PROVIDER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tralebot-secrets
                  key: TRALEBOT_PAYMENT_PROVIDER_TOKEN
            - name: TRALEBOT_DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: tralebot-secrets
                  key: TRALEBOT_DB_CONNECTION_STRING
            - name: TRALEBOT_OPENAI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tralebot-secrets
                  key: TRALEBOT_OPENAI_TOKEN

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tralebot-ingress
spec:
  rules:
    - host: tralebot.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tralebot-service
                port:
                  number: 80

---

apiVersion: v1
kind: Secret
metadata:
  name: tralebot-secrets
type: Opaque
data:
  TRALEBOT_CONFIGURATION_TOKEN: {{ TRALEBOT_CONFIGURATION_TOKEN | b64enc | quote }}
  TRALEBOT_SERVER_HOST: {{ TRALEBOT_SERVER_HOST | b64enc | quote }}
  TRALEBOT_WEBHOOK_TOKEN: {{ TRALEBOT_WEBHOOK_TOKEN | b64enc | quote }}
  TRALEBOT_PAYMENT_PROVIDER_TOKEN: {{ TRALEBOT_PAYMENT_PROVIDER_TOKEN | b64enc | quote }}
  TRALEBOT_DB_CONNECTION_STRING: {{ TRALEBOT_DB_CONNECTION_STRING | b64enc | quote }}
  TRALEBOT_OPENAI_TOKEN: {{ TRALEBOT_OPENAI_TOKEN | b64enc | quote }}

---