name: Configure docker-compose for app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    #  - uses: actions/checkout@v3
      - shell: bash
        env:
          TRALEBOT_SERVER_HOST: ${{ secrets.TRALEBOT_SERVER_HOST }}
        run: |
          echo "BotConfiguration__HostAddress=$TRALEBOT_SERVER_HOST" > test.txt
          echo "BotConfiguration__Token=$TRALEBOT_SERVER_HOST" >> test.txt
        
      - name: Copy file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: test.txt
#         Before copy you write this command on server: 
#         1) sudo chown username: myfolder (folder on server with docke-compose: tralebot)
#         2) sudo chmod u+w myfolder
          remote: ../../usr/local/tralebot/test.txt
          host: ${{ secrets.TRALEBOT_SERVER_HOST }}
          username: ${{ secrets.TRALEBOT_SERVER_USERNAME }}
          password: ${{ secrets.TRALEBOT_SERVER_USER_PASSWORD }}
