name: Copy docker-compose files to server

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Copy docker-compose files from branch:'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.inputs.branch_name }}'
        
      - name: Copy docker-compose files to server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: deploy
#         Before copy file to server you should execute this command on the server: 
#         1) sudo chown username: myfolder (folder on server with docke-compose: tralebot)
#         2) sudo chmod u+w myfolder
          remote: ../../usr/local/tralebot
          host: ${{ secrets.TRALEBOT_SERVER_HOST }}
          username: ${{ secrets.TRALEBOT_SERVER_USERNAME }}
          password: ${{ secrets.TRALEBOT_SERVER_USER_PASSWORD }}
