name: Build and push docker image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: undermove/tralebot:latest
      
      - 
        name: Connect to server and restart TraleBot
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.TRALEBOT_SERVER_HOST }}
          username: ${{ secrets.TRALEBOT_SERVER_USERNAME }}
          password: ${{ secrets.TRALEBOT_SERVER_USER_PASSWORD }}
          port: ${{ secrets.TRALEBOT_SERVER_PORT }}
          script: |
           cd ../../usr/local/tralebot/
           docker-compose down
           sleep 5
           docker-compose up
